# Generated by Django 6.0.7 on 2026-08-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.URLField(verbose_name='Capa'),
        ),
    ]
