# Generated by Django 6.0.7 on 2026-07-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True, verbose_name='Preço'),
        ),
    ]
