# Generated by Django 6.0.7 on 2026-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_carrinho_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
