# Generated by Django 6.0.7 on 2026-07-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_alter_carrinho_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinho',
            old_name='item',
            new_name='livro',
        ),
        migrations.RemoveField(
            model_name='carrinho',
            name='preco',
        ),
    ]
