# Generated by Django 6.0.7 on 2026-08-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeDesejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adicionado_em', models.DateTimeField(auto_now_add=True, verbose_name='Adicionado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.livro', verbose_name='Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'lista de desejos',
                'verbose_name_plural': 'listas de desejos',
                'unique_together': {('usuario', 'item')},
            },
        ),
    ]
