# Generated by Django 6.0.7 on 2026-08-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_livro_capa'),
        ('lista_desejos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listadedesejos',
            options={'ordering': ['-adicionado_em'], 'verbose_name': 'lista de desejos', 'verbose_name_plural': 'listas de desejos'},
        ),
        migrations.RenameField(
            model_name='listadedesejos',
            old_name='item',
            new_name='livro',
        ),
        migrations.AlterUniqueTogether(
            name='listadedesejos',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='listadedesejos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='listadedesejos',
            unique_together={('usuario', 'livro')},
        ),
        migrations.AddIndex(
            model_name='listadedesejos',
            index=models.Index(fields=['usuario', 'livro'], name='lista_desej_usuario_a47297_idx'),
        ),
    ]
