# Generated by Django 6.0.7 on 2026-08-08 13:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endereco',
            options={'ordering': ['-principal', '-created_at'], 'verbose_name': 'Endereco', 'verbose_name_plural': 'Enderecos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['-data_joined'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AddField(
            model_name='endereco',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-?d{3}$', 'CEP deve ser no formato XXXX-XXX ou XXXXXXX')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, help_text='Apto, block, etc', max_length=100, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nome_completo',
            field=models.CharField(help_text='Quem vai receber o pedido', max_length=200, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=False, verbose_name='É o endereço principal?'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(blank=True, help_text='Ex: próximo ao mercado', max_length=200, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=200, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Dafa de nascimento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Usuários inativos não podem fazer login', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'O Telefone deve ter entre 9 e 15 dígitos')], verbose_name='Telefone'),
        ),
        migrations.AlterUniqueTogether(
            name='endereco',
            unique_together={('usuario', 'numero', 'rua', 'cidade')},
        ),
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['usuario', 'principal'], name='accounts_en_usuario_a511a4_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['email'], name='accounts_us_email_6213b5_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['-data_joined'], name='accounts_us_data_jo_b5735e_idx'),
        ),
    ]
