# Generated by Django 6.0.7 on 2026-08-08 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_endereco_options_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-?\\d{3}$', 'CEP deve ser no formato XXXXX-XXX ou XXXXXXXX')], verbose_name='CEP'),
        ),
    ]
