# Generated by Django 6.0.7 on 2026-08-08 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('/^(?:\\(\\d{2}\\)\\s?|(\\d{2}))9\\d{4}-?\\d{4}$/', 'O Telefone deve o formato (11)91234-5678 ou 11912345678')], verbose_name='Telefone'),
        ),
    ]
